// @ts-nocheck
// This file is auto-generated by scripts/save-plugins-import.ts. Do not edit this file manually.
// To update, run: bun run plugins:save

export const PLUGINS_INFO = {
  "@rtqs/plugin-ill-undraw": {
    "name": "@rtqs/plugin-ill-undraw",
    "description": "Adaptation of Undraw illustrations",
    "version": "0.0.1-dev.1",
    "type": "illustration",
    "status": "beta",
    "targetVersion": "0",
    "scope": [
      "web-client"
    ]
  },
  "@rtqs/plugin-icons-tabler": {
    "name": "@rtqs/plugin-icons-tabler",
    "description": "Adaptation of Tabler Icons",
    "version": "0.0.1-dev.1",
    "type": "icon",
    "status": "beta",
    "targetVersion": "0",
    "scope": [
      "web-client"
    ]
  },
  "@rtqs/plugin-theme-violet-bloom": {
    "name": "@rtqs/plugin-theme-violet-bloom",
    "description": "Adaptation of Violet Bloom theme from @tweakcn",
    "version": "0.0.1-dev.1",
    "type": "raw",
    "status": "beta",
    "targetVersion": "0",
    "scope": [
      "web-client"
    ]
  },
  "@rtqs/plugin-theme-northen-lights": {
    "name": "@rtqs/plugin-theme-northen-lights",
    "description": "Adaptation of Northen Lights Theme from https://tweakcn.com/",
    "version": "0.0.1-dev.1",
    "type": "raw",
    "status": "beta",
    "targetVersion": "0",
    "scope": [
      "web-client"
    ]
  }
} as const;

export type PluginsInfo = typeof PLUGINS_INFO;
