// @ts-nocheck
// This file is auto-generated by scripts/save-plugins-import.ts. Do not edit this file manually.
// To update the plugins, Run: bun run plugins:save
export const PLUGINS: Record<string, () => Promise<any>> = {
  "@rtqs/plugin-ill-undraw": () => import("@rtqs/plugin-ill-undraw"),
  "@rtqs/plugin-icons-tabler": () => import("@rtqs/plugin-icons-tabler"),
  "@rtqs/plugin-theme-violet-bloom": () => import("@rtqs/plugin-theme-violet-bloom"),
  "@rtqs/plugin-theme-northen-lights": () => import("@rtqs/plugin-theme-northen-lights"),
};
