/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TempRouteImport } from './routes/temp'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as UsersRouteImport } from './routes/_users'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as UsersIndexRouteImport } from './routes/_users/index'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminReviewIndexRouteImport } from './routes/admin/review/index'
import { Route as AdminQuizzesIndexRouteImport } from './routes/admin/quizzes/index'
import { Route as AdminLobbyIndexRouteImport } from './routes/admin/lobby/index'
import { Route as AdminQuizzesQuizIdRouteImport } from './routes/admin/quizzes/$quiz-id'
import { Route as AdminLobbyLobbyIdRouteImport } from './routes/admin/lobby/$lobby-id'
import { Route as UsersLobbyLobbyIdRouteImport } from './routes/_users/lobby/$lobby-id'

const TempRoute = TempRouteImport.update({
  id: '/temp',
  path: '/temp',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersRoute = UsersRouteImport.update({
  id: '/_users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const UsersIndexRoute = UsersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UsersRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReviewIndexRoute = AdminReviewIndexRouteImport.update({
  id: '/review/',
  path: '/review/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminQuizzesIndexRoute = AdminQuizzesIndexRouteImport.update({
  id: '/quizzes/',
  path: '/quizzes/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLobbyIndexRoute = AdminLobbyIndexRouteImport.update({
  id: '/lobby/',
  path: '/lobby/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminQuizzesQuizIdRoute = AdminQuizzesQuizIdRouteImport.update({
  id: '/quizzes/$quiz-id',
  path: '/quizzes/$quiz-id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLobbyLobbyIdRoute = AdminLobbyLobbyIdRouteImport.update({
  id: '/lobby/$lobby-id',
  path: '/lobby/$lobby-id',
  getParentRoute: () => AdminRoute,
} as any)
const UsersLobbyLobbyIdRoute = UsersLobbyLobbyIdRouteImport.update({
  id: '/lobby/$lobby-id',
  path: '/lobby/$lobby-id',
  getParentRoute: () => UsersRoute,
} as any)

export interface FileRoutesByFullPath {
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/temp': typeof TempRoute
  '/admin/users': typeof AdminUsersRoute
  '/': typeof UsersIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/lobby/$lobby-id': typeof UsersLobbyLobbyIdRoute
  '/admin/lobby/$lobby-id': typeof AdminLobbyLobbyIdRoute
  '/admin/quizzes/$quiz-id': typeof AdminQuizzesQuizIdRoute
  '/admin/lobby': typeof AdminLobbyIndexRoute
  '/admin/quizzes': typeof AdminQuizzesIndexRoute
  '/admin/review': typeof AdminReviewIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/temp': typeof TempRoute
  '/admin/users': typeof AdminUsersRoute
  '/': typeof UsersIndexRoute
  '/admin': typeof AdminIndexRoute
  '/lobby/$lobby-id': typeof UsersLobbyLobbyIdRoute
  '/admin/lobby/$lobby-id': typeof AdminLobbyLobbyIdRoute
  '/admin/quizzes/$quiz-id': typeof AdminQuizzesQuizIdRoute
  '/admin/lobby': typeof AdminLobbyIndexRoute
  '/admin/quizzes': typeof AdminQuizzesIndexRoute
  '/admin/review': typeof AdminReviewIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_users': typeof UsersRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/temp': typeof TempRoute
  '/admin/users': typeof AdminUsersRoute
  '/_users/': typeof UsersIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/_users/lobby/$lobby-id': typeof UsersLobbyLobbyIdRoute
  '/admin/lobby/$lobby-id': typeof AdminLobbyLobbyIdRoute
  '/admin/quizzes/$quiz-id': typeof AdminQuizzesQuizIdRoute
  '/admin/lobby/': typeof AdminLobbyIndexRoute
  '/admin/quizzes/': typeof AdminQuizzesIndexRoute
  '/admin/review/': typeof AdminReviewIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/admin'
    | '/login'
    | '/temp'
    | '/admin/users'
    | '/'
    | '/admin/'
    | '/lobby/$lobby-id'
    | '/admin/lobby/$lobby-id'
    | '/admin/quizzes/$quiz-id'
    | '/admin/lobby'
    | '/admin/quizzes'
    | '/admin/review'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/temp'
    | '/admin/users'
    | '/'
    | '/admin'
    | '/lobby/$lobby-id'
    | '/admin/lobby/$lobby-id'
    | '/admin/quizzes/$quiz-id'
    | '/admin/lobby'
    | '/admin/quizzes'
    | '/admin/review'
  id:
    | '__root__'
    | '/_users'
    | '/admin'
    | '/login'
    | '/temp'
    | '/admin/users'
    | '/_users/'
    | '/admin/'
    | '/_users/lobby/$lobby-id'
    | '/admin/lobby/$lobby-id'
    | '/admin/quizzes/$quiz-id'
    | '/admin/lobby/'
    | '/admin/quizzes/'
    | '/admin/review/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  UsersRoute: typeof UsersRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
  TempRoute: typeof TempRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/temp': {
      id: '/temp'
      path: '/temp'
      fullPath: '/temp'
      preLoaderRoute: typeof TempRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_users': {
      id: '/_users'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_users/': {
      id: '/_users/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof UsersIndexRouteImport
      parentRoute: typeof UsersRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/review/': {
      id: '/admin/review/'
      path: '/review'
      fullPath: '/admin/review'
      preLoaderRoute: typeof AdminReviewIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/quizzes/': {
      id: '/admin/quizzes/'
      path: '/quizzes'
      fullPath: '/admin/quizzes'
      preLoaderRoute: typeof AdminQuizzesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/lobby/': {
      id: '/admin/lobby/'
      path: '/lobby'
      fullPath: '/admin/lobby'
      preLoaderRoute: typeof AdminLobbyIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/quizzes/$quiz-id': {
      id: '/admin/quizzes/$quiz-id'
      path: '/quizzes/$quiz-id'
      fullPath: '/admin/quizzes/$quiz-id'
      preLoaderRoute: typeof AdminQuizzesQuizIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/lobby/$lobby-id': {
      id: '/admin/lobby/$lobby-id'
      path: '/lobby/$lobby-id'
      fullPath: '/admin/lobby/$lobby-id'
      preLoaderRoute: typeof AdminLobbyLobbyIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_users/lobby/$lobby-id': {
      id: '/_users/lobby/$lobby-id'
      path: '/lobby/$lobby-id'
      fullPath: '/lobby/$lobby-id'
      preLoaderRoute: typeof UsersLobbyLobbyIdRouteImport
      parentRoute: typeof UsersRoute
    }
  }
}

interface UsersRouteChildren {
  UsersIndexRoute: typeof UsersIndexRoute
  UsersLobbyLobbyIdRoute: typeof UsersLobbyLobbyIdRoute
}

const UsersRouteChildren: UsersRouteChildren = {
  UsersIndexRoute: UsersIndexRoute,
  UsersLobbyLobbyIdRoute: UsersLobbyLobbyIdRoute,
}

const UsersRouteWithChildren = UsersRoute._addFileChildren(UsersRouteChildren)

interface AdminRouteChildren {
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminLobbyLobbyIdRoute: typeof AdminLobbyLobbyIdRoute
  AdminQuizzesQuizIdRoute: typeof AdminQuizzesQuizIdRoute
  AdminLobbyIndexRoute: typeof AdminLobbyIndexRoute
  AdminQuizzesIndexRoute: typeof AdminQuizzesIndexRoute
  AdminReviewIndexRoute: typeof AdminReviewIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminLobbyLobbyIdRoute: AdminLobbyLobbyIdRoute,
  AdminQuizzesQuizIdRoute: AdminQuizzesQuizIdRoute,
  AdminLobbyIndexRoute: AdminLobbyIndexRoute,
  AdminQuizzesIndexRoute: AdminQuizzesIndexRoute,
  AdminReviewIndexRoute: AdminReviewIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  UsersRoute: UsersRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
  TempRoute: TempRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
