/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TempRouteImport } from './routes/temp'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as LobbyLobbyIdRouteImport } from './routes/lobby/$lobby-id'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminPlayQuizRouteImport } from './routes/admin/play-quiz'
import { Route as AdminReviewIndexRouteImport } from './routes/admin/review/index'
import { Route as AdminQuizzesIndexRouteImport } from './routes/admin/quizzes/index'
import { Route as AdminQuizzesQuizIdRouteImport } from './routes/admin/quizzes/$quiz-id'
import { Route as AdminLobbyLobbyIdRouteImport } from './routes/admin/lobby/$lobby-id'

const TempRoute = TempRouteImport.update({
  id: '/temp',
  path: '/temp',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const LobbyLobbyIdRoute = LobbyLobbyIdRouteImport.update({
  id: '/lobby/$lobby-id',
  path: '/lobby/$lobby-id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPlayQuizRoute = AdminPlayQuizRouteImport.update({
  id: '/play-quiz',
  path: '/play-quiz',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReviewIndexRoute = AdminReviewIndexRouteImport.update({
  id: '/review/',
  path: '/review/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminQuizzesIndexRoute = AdminQuizzesIndexRouteImport.update({
  id: '/quizzes/',
  path: '/quizzes/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminQuizzesQuizIdRoute = AdminQuizzesQuizIdRouteImport.update({
  id: '/quizzes/$quiz-id',
  path: '/quizzes/$quiz-id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLobbyLobbyIdRoute = AdminLobbyLobbyIdRouteImport.update({
  id: '/lobby/$lobby-id',
  path: '/lobby/$lobby-id',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/temp': typeof TempRoute
  '/admin/play-quiz': typeof AdminPlayQuizRoute
  '/admin/users': typeof AdminUsersRoute
  '/lobby/$lobby-id': typeof LobbyLobbyIdRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/lobby/$lobby-id': typeof AdminLobbyLobbyIdRoute
  '/admin/quizzes/$quiz-id': typeof AdminQuizzesQuizIdRoute
  '/admin/quizzes': typeof AdminQuizzesIndexRoute
  '/admin/review': typeof AdminReviewIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/temp': typeof TempRoute
  '/admin/play-quiz': typeof AdminPlayQuizRoute
  '/admin/users': typeof AdminUsersRoute
  '/lobby/$lobby-id': typeof LobbyLobbyIdRoute
  '/admin': typeof AdminIndexRoute
  '/admin/lobby/$lobby-id': typeof AdminLobbyLobbyIdRoute
  '/admin/quizzes/$quiz-id': typeof AdminQuizzesQuizIdRoute
  '/admin/quizzes': typeof AdminQuizzesIndexRoute
  '/admin/review': typeof AdminReviewIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/temp': typeof TempRoute
  '/admin/play-quiz': typeof AdminPlayQuizRoute
  '/admin/users': typeof AdminUsersRoute
  '/lobby/$lobby-id': typeof LobbyLobbyIdRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/lobby/$lobby-id': typeof AdminLobbyLobbyIdRoute
  '/admin/quizzes/$quiz-id': typeof AdminQuizzesQuizIdRoute
  '/admin/quizzes/': typeof AdminQuizzesIndexRoute
  '/admin/review/': typeof AdminReviewIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/temp'
    | '/admin/play-quiz'
    | '/admin/users'
    | '/lobby/$lobby-id'
    | '/admin/'
    | '/admin/lobby/$lobby-id'
    | '/admin/quizzes/$quiz-id'
    | '/admin/quizzes'
    | '/admin/review'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/temp'
    | '/admin/play-quiz'
    | '/admin/users'
    | '/lobby/$lobby-id'
    | '/admin'
    | '/admin/lobby/$lobby-id'
    | '/admin/quizzes/$quiz-id'
    | '/admin/quizzes'
    | '/admin/review'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/login'
    | '/temp'
    | '/admin/play-quiz'
    | '/admin/users'
    | '/lobby/$lobby-id'
    | '/admin/'
    | '/admin/lobby/$lobby-id'
    | '/admin/quizzes/$quiz-id'
    | '/admin/quizzes/'
    | '/admin/review/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
  TempRoute: typeof TempRoute
  LobbyLobbyIdRoute: typeof LobbyLobbyIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/temp': {
      id: '/temp'
      path: '/temp'
      fullPath: '/temp'
      preLoaderRoute: typeof TempRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/lobby/$lobby-id': {
      id: '/lobby/$lobby-id'
      path: '/lobby/$lobby-id'
      fullPath: '/lobby/$lobby-id'
      preLoaderRoute: typeof LobbyLobbyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/play-quiz': {
      id: '/admin/play-quiz'
      path: '/play-quiz'
      fullPath: '/admin/play-quiz'
      preLoaderRoute: typeof AdminPlayQuizRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/review/': {
      id: '/admin/review/'
      path: '/review'
      fullPath: '/admin/review'
      preLoaderRoute: typeof AdminReviewIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/quizzes/': {
      id: '/admin/quizzes/'
      path: '/quizzes'
      fullPath: '/admin/quizzes'
      preLoaderRoute: typeof AdminQuizzesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/quizzes/$quiz-id': {
      id: '/admin/quizzes/$quiz-id'
      path: '/quizzes/$quiz-id'
      fullPath: '/admin/quizzes/$quiz-id'
      preLoaderRoute: typeof AdminQuizzesQuizIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/lobby/$lobby-id': {
      id: '/admin/lobby/$lobby-id'
      path: '/lobby/$lobby-id'
      fullPath: '/admin/lobby/$lobby-id'
      preLoaderRoute: typeof AdminLobbyLobbyIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminPlayQuizRoute: typeof AdminPlayQuizRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminLobbyLobbyIdRoute: typeof AdminLobbyLobbyIdRoute
  AdminQuizzesQuizIdRoute: typeof AdminQuizzesQuizIdRoute
  AdminQuizzesIndexRoute: typeof AdminQuizzesIndexRoute
  AdminReviewIndexRoute: typeof AdminReviewIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminPlayQuizRoute: AdminPlayQuizRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminLobbyLobbyIdRoute: AdminLobbyLobbyIdRoute,
  AdminQuizzesQuizIdRoute: AdminQuizzesQuizIdRoute,
  AdminQuizzesIndexRoute: AdminQuizzesIndexRoute,
  AdminReviewIndexRoute: AdminReviewIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
  TempRoute: TempRoute,
  LobbyLobbyIdRoute: LobbyLobbyIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
