/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * API Docs | Google Maestro | 0.0.1 | @alpha
 * OpenAPI spec version: 0.0.1
 */
import { apiClient } from '../axios';
export interface CreateQuizDto {
  /** Name of quiz */
  name: string;
  description?: string;
}

export interface QuizDto {
  id: string;
  createdAt: string;
  updatedAt: string;
  name: string;
  description?: string;
}

export interface SuccessResponseTypeDtoQuizDto1 {
  /** HTTP status code */
  statusCode: number;
  /** Response message */
  message: string;
  /** Created successfully */
  data: QuizDto;
}

export interface SuccessResponseTypeDtoQuizDto2 {
  /** HTTP status code */
  statusCode: number;
  /** Response message */
  message: string;
  /** Retrieved successfully */
  data: QuizDto[];
}

export interface SuccessResponseTypeDtoQuizDto3 {
  /** HTTP status code */
  statusCode: number;
  /** Response message */
  message: string;
  /** Retrieved successfully */
  data: QuizDto;
}

export interface UpdateQuizDto {
  /** Name of quiz */
  name?: string;
  description?: string;
  /**  Id of the quiz to update */
  id: string;
}

export interface SuccessResponseTypeDtoQuizDto4 {
  /** HTTP status code */
  statusCode: number;
  /** Response message */
  message: string;
  /** Updated successfully */
  data: QuizDto;
}

export interface ApiResponseBaseDto {
  /** HTTP status code */
  statusCode: number;
  /** Response message */
  message: string;
}

export interface CreateQuizModuleDto {
  /** Name of the Module */
  name: string;
  /**
   * The order of model, first to last ie 0 to ...
   * @minimum 0
   */
  index: number;
  /** Id of the quiz to which this model is related */
  quizId: string;
}

export interface QuizModuleDto {
  id: string;
  createdAt: string;
  updatedAt: string;
  name: string;
  index: number;
  quizId: string;
}

export interface SuccessResponseTypeDtoQuizModuleDto5 {
  /** HTTP status code */
  statusCode: number;
  /** Response message */
  message: string;
  /** Created successfully */
  data: QuizModuleDto;
}

export interface SuccessResponseTypeDtoQuizModuleDto6 {
  /** HTTP status code */
  statusCode: number;
  /** Response message */
  message: string;
  /** Retrieved successfully */
  data: QuizModuleDto[];
}

export interface UpdateQuizModuleDto {
  /** Name of the Module */
  name?: string;
  /**
   * The order of model, first to last ie 0 to ...
   * @minimum 0
   */
  index?: number;
  /** Id of the quiz to which this model is related */
  quizId?: string;
  /**  Id of the quiz module to update */
  id: string;
}

export interface SuccessResponseTypeDtoQuizModuleDto7 {
  /** HTTP status code */
  statusCode: number;
  /** Response message */
  message: string;
  /** Updated successfully */
  data: QuizModuleDto;
}

export interface QuizQuestionDto {
  /** Question */
  question: string;
  /** Correct answer of the question */
  answer: string;
  /** Order of the question */
  index: number;
  /** The module in which the question lies */
  moduleId: string;
}

export interface AddQuizQuestionsDto {
  questions: QuizQuestionDto[];
}

export interface SuccessResponseTypeDtoQuizQuestionDto8 {
  /** HTTP status code */
  statusCode: number;
  /** Response message */
  message: string;
  /** Created successfully */
  data: QuizQuestionDto[];
}

export interface SuccessResponseTypeDtoQuizQuestionDto9 {
  /** HTTP status code */
  statusCode: number;
  /** Response message */
  message: string;
  /** Retrieved successfully */
  data: QuizQuestionDto[];
}

export interface UpdateQuizQuestionDto {
  /** Question */
  question?: string;
  /** Correct answer of the question */
  answer?: string;
  /** Order of the question */
  index?: number;
  /** The module in which the question lies */
  moduleId?: string;
  /**  Id of the question to update */
  id: string;
}

export interface SuccessResponseTypeDtoQuizQuestionDto10 {
  /** HTTP status code */
  statusCode: number;
  /** Response message */
  message: string;
  /** Updated successfully */
  data: QuizQuestionDto;
}

export interface OnCreateLobbyDto {
  /** The ID of the quiz to be played in the lobby */
  quizId: string;
  /** The date and time when the game will start */
  waitUntil: string;
  /** The unique code for the lobby */
  code: string;
}

export type QuizzesControllerDeleteQuizzesParams = {
/**
 * @minLength 1
 */
ids: string[];
};

export type QuizModulesControllerListQuizModulesParams = {
/**
 *  Id of the quiz to to list modules for
 */
id: string;
};

export type QuizModulesControllerDeleteQuizModulesParams = {
/**
 * @minLength 1
 */
ids: string[];
};

export type QuizQuestionsControllerListQuizQuestionsParams = {
/**
 *  Id of the module to list the questions for
 */
moduleId: string;
};

export type QuizQuestionsControllerDeleteQuizQuestionsParams = {
/**
 * @minLength 1
 */
ids: string[];
};

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  export const getAPIDocsGoogleMaestro001Alpha = () => {
const appControllerGetHello = (
    
 options?: SecondParameter<typeof apiClient<void>>,) => {
      return apiClient<void>(
      {url: `/api`, method: 'GET'
    },
      options);
    }
  
/**
 * No description available
 * @summary Create a quiz
 */
const quizzesControllerCreateQuiz = (
    createQuizDto: CreateQuizDto,
 options?: SecondParameter<typeof apiClient<SuccessResponseTypeDtoQuizDto1>>,) => {
      return apiClient<SuccessResponseTypeDtoQuizDto1>(
      {url: `/api/quizzes`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createQuizDto
    },
      options);
    }
  
/**
 * No description available
 * @summary List all avaliable quizes
 */
const quizzesControllerListQuizzes = (
    
 options?: SecondParameter<typeof apiClient<SuccessResponseTypeDtoQuizDto2>>,) => {
      return apiClient<SuccessResponseTypeDtoQuizDto2>(
      {url: `/api/quizzes`, method: 'GET'
    },
      options);
    }
  
/**
 * No description available
 * @summary Update quiz
 */
const quizzesControllerUpdateQuiz = (
    updateQuizDto: UpdateQuizDto,
 options?: SecondParameter<typeof apiClient<SuccessResponseTypeDtoQuizDto4>>,) => {
      return apiClient<SuccessResponseTypeDtoQuizDto4>(
      {url: `/api/quizzes`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: updateQuizDto
    },
      options);
    }
  
/**
 * No description available
 * @summary Delete quizzes by givn IDs
 */
const quizzesControllerDeleteQuizzes = (
    params: QuizzesControllerDeleteQuizzesParams,
 options?: SecondParameter<typeof apiClient<ApiResponseBaseDto>>,) => {
      return apiClient<ApiResponseBaseDto>(
      {url: `/api/quizzes`, method: 'DELETE',
        params
    },
      options);
    }
  
/**
 * No description available
 * @summary Get a quiz
 */
const quizzesControllerGetAQuiz = (
    quizId: string,
 options?: SecondParameter<typeof apiClient<SuccessResponseTypeDtoQuizDto3>>,) => {
      return apiClient<SuccessResponseTypeDtoQuizDto3>(
      {url: `/api/quizzes/${quizId}`, method: 'GET'
    },
      options);
    }
  
/**
 * No description available
 * @summary Add a quiz module
 */
const quizModulesControllerCreateQuizModule = (
    createQuizModuleDto: CreateQuizModuleDto,
 options?: SecondParameter<typeof apiClient<SuccessResponseTypeDtoQuizModuleDto5>>,) => {
      return apiClient<SuccessResponseTypeDtoQuizModuleDto5>(
      {url: `/api/quiz/modules`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createQuizModuleDto
    },
      options);
    }
  
/**
 * 
Lists all the available modules for the given quiz, ordered by lowest index ie 0 first

 * @summary List quiz modules
 */
const quizModulesControllerListQuizModules = (
    params: QuizModulesControllerListQuizModulesParams,
 options?: SecondParameter<typeof apiClient<SuccessResponseTypeDtoQuizModuleDto6>>,) => {
      return apiClient<SuccessResponseTypeDtoQuizModuleDto6>(
      {url: `/api/quiz/modules`, method: 'GET',
        params
    },
      options);
    }
  
/**
 * No description available
 * @summary Update quiz module
 */
const quizModulesControllerUpdateQuizModule = (
    updateQuizModuleDto: UpdateQuizModuleDto,
 options?: SecondParameter<typeof apiClient<SuccessResponseTypeDtoQuizModuleDto7>>,) => {
      return apiClient<SuccessResponseTypeDtoQuizModuleDto7>(
      {url: `/api/quiz/modules`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: updateQuizModuleDto
    },
      options);
    }
  
/**
 * No description available
 * @summary Delete quiz modules
 */
const quizModulesControllerDeleteQuizModules = (
    params: QuizModulesControllerDeleteQuizModulesParams,
 options?: SecondParameter<typeof apiClient<ApiResponseBaseDto>>,) => {
      return apiClient<ApiResponseBaseDto>(
      {url: `/api/quiz/modules`, method: 'DELETE',
        params
    },
      options);
    }
  
/**
 * No description available
 * @summary Add mutiple questions to a module
 */
const quizQuestionsControllerAddQuizQuestions = (
    addQuizQuestionsDto: AddQuizQuestionsDto,
 options?: SecondParameter<typeof apiClient<SuccessResponseTypeDtoQuizQuestionDto8>>,) => {
      return apiClient<SuccessResponseTypeDtoQuizQuestionDto8>(
      {url: `/api/quiz/questions`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: addQuizQuestionsDto
    },
      options);
    }
  
/**
 * 
Lists all the available question for the given module, ordered by lowest index ie 0 first

 * @summary List quiz questions
 */
const quizQuestionsControllerListQuizQuestions = (
    params: QuizQuestionsControllerListQuizQuestionsParams,
 options?: SecondParameter<typeof apiClient<SuccessResponseTypeDtoQuizQuestionDto9>>,) => {
      return apiClient<SuccessResponseTypeDtoQuizQuestionDto9>(
      {url: `/api/quiz/questions`, method: 'GET',
        params
    },
      options);
    }
  
/**
 * No description available
 * @summary Update a question
 */
const quizQuestionsControllerUpdateQuizQuestion = (
    updateQuizQuestionDto: UpdateQuizQuestionDto,
 options?: SecondParameter<typeof apiClient<SuccessResponseTypeDtoQuizQuestionDto10>>,) => {
      return apiClient<SuccessResponseTypeDtoQuizQuestionDto10>(
      {url: `/api/quiz/questions`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: updateQuizQuestionDto
    },
      options);
    }
  
/**
 * No description available
 * @summary Delete quiz questions
 */
const quizQuestionsControllerDeleteQuizQuestions = (
    params: QuizQuestionsControllerDeleteQuizQuestionsParams,
 options?: SecondParameter<typeof apiClient<ApiResponseBaseDto>>,) => {
      return apiClient<ApiResponseBaseDto>(
      {url: `/api/quiz/questions`, method: 'DELETE',
        params
    },
      options);
    }
  
return {appControllerGetHello,quizzesControllerCreateQuiz,quizzesControllerListQuizzes,quizzesControllerUpdateQuiz,quizzesControllerDeleteQuizzes,quizzesControllerGetAQuiz,quizModulesControllerCreateQuizModule,quizModulesControllerListQuizModules,quizModulesControllerUpdateQuizModule,quizModulesControllerDeleteQuizModules,quizQuestionsControllerAddQuizQuestions,quizQuestionsControllerListQuizQuestions,quizQuestionsControllerUpdateQuizQuestion,quizQuestionsControllerDeleteQuizQuestions}};
export type AppControllerGetHelloResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAPIDocsGoogleMaestro001Alpha>['appControllerGetHello']>>>
export type QuizzesControllerCreateQuizResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAPIDocsGoogleMaestro001Alpha>['quizzesControllerCreateQuiz']>>>
export type QuizzesControllerListQuizzesResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAPIDocsGoogleMaestro001Alpha>['quizzesControllerListQuizzes']>>>
export type QuizzesControllerUpdateQuizResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAPIDocsGoogleMaestro001Alpha>['quizzesControllerUpdateQuiz']>>>
export type QuizzesControllerDeleteQuizzesResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAPIDocsGoogleMaestro001Alpha>['quizzesControllerDeleteQuizzes']>>>
export type QuizzesControllerGetAQuizResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAPIDocsGoogleMaestro001Alpha>['quizzesControllerGetAQuiz']>>>
export type QuizModulesControllerCreateQuizModuleResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAPIDocsGoogleMaestro001Alpha>['quizModulesControllerCreateQuizModule']>>>
export type QuizModulesControllerListQuizModulesResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAPIDocsGoogleMaestro001Alpha>['quizModulesControllerListQuizModules']>>>
export type QuizModulesControllerUpdateQuizModuleResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAPIDocsGoogleMaestro001Alpha>['quizModulesControllerUpdateQuizModule']>>>
export type QuizModulesControllerDeleteQuizModulesResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAPIDocsGoogleMaestro001Alpha>['quizModulesControllerDeleteQuizModules']>>>
export type QuizQuestionsControllerAddQuizQuestionsResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAPIDocsGoogleMaestro001Alpha>['quizQuestionsControllerAddQuizQuestions']>>>
export type QuizQuestionsControllerListQuizQuestionsResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAPIDocsGoogleMaestro001Alpha>['quizQuestionsControllerListQuizQuestions']>>>
export type QuizQuestionsControllerUpdateQuizQuestionResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAPIDocsGoogleMaestro001Alpha>['quizQuestionsControllerUpdateQuizQuestion']>>>
export type QuizQuestionsControllerDeleteQuizQuestionsResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAPIDocsGoogleMaestro001Alpha>['quizQuestionsControllerDeleteQuizQuestions']>>>
