/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * API Docs | Google Maestro | 0.0.1 | @alpha
 * ---
---

## API Overview

The API supports four types of routes:

### 1. POST (Create)

Creates a new document in the database and returns a success response upon completion.

### 2. GET (Read)

Retrieves documents based on optional filter criteria.

### 3. DELETE

Removes documents matching specified filters and returns the ID of the deleted document.

### 4. PATCH (Update)

Updates an existing document, typically identified by its document ID.

## Authentication

Authentication is managed using Better Auth with the `magic-link` and `admin` plugins.  
Refer to the documentation here: [Better Auth](https://www.better-auth.com/)

 * OpenAPI spec version: 0.0.1
 */
import { apiClient } from "../axios";
export interface CreateQuizDto {
  /** Name of quiz */
  name: string;
  description?: string;
}

export interface QuizDto {
  id: string;
  createdAt: string;
  updatedAt: string;
  /** Name of quiz */
  name: string;
  description?: string;
}

export interface SuccessResponseTypeDtoQuizDto1 {
  /** HTTP status code */
  statusCode: number;
  /** Response message */
  message: string;
  /** Created successfully */
  data: QuizDto;
}

export interface SuccessResponseTypeDtoQuizDto2 {
  /** HTTP status code */
  statusCode: number;
  /** Response message */
  message: string;
  /** Retrieved successfully */
  data: QuizDto[];
}

export interface SuccessResponseTypeDtoQuizDto3 {
  /** HTTP status code */
  statusCode: number;
  /** Response message */
  message: string;
  /** Retrieved successfully */
  data: QuizDto;
}

export interface UpdateQuizDto {
  /** Name of quiz */
  name?: string;
  description?: string;
  /** Id of quiz to update */
  id: string;
}

export interface SuccessResponseTypeDtoQuizDto4 {
  /** HTTP status code */
  statusCode: number;
  /** Response message */
  message: string;
  /** Updated successfully */
  data: QuizDto;
}

export interface SuccessResponseTypeDtoString5 {
  /** HTTP status code */
  statusCode: number;
  /** Response message */
  message: string;
  /** Deleted successfully */
  data: string[];
}

export interface CreateQuizModuleDto {
  /** Name of quiz module */
  name: string;
  index: number;
  /** Quiz id of this module */
  quizId: string;
}

export interface QuizModuleDto {
  id: string;
  createdAt: string;
  updatedAt: string;
  /** Name of quiz module */
  name: string;
  index: number;
}

export interface SuccessResponseTypeDtoQuizModuleDto6 {
  /** HTTP status code */
  statusCode: number;
  /** Response message */
  message: string;
  /** Created successfully */
  data: QuizModuleDto;
}

export interface SuccessResponseTypeDtoQuizModuleDto7 {
  /** HTTP status code */
  statusCode: number;
  /** Response message */
  message: string;
  /** Retrieved successfully */
  data: QuizModuleDto[];
}

export interface SuccessResponseTypeDtoQuizModuleDto8 {
  /** HTTP status code */
  statusCode: number;
  /** Response message */
  message: string;
  /** Retrieved successfully */
  data: QuizModuleDto;
}

export interface UpdateQuizModuleDto {
  /** Name of quiz module */
  name?: string;
  index?: number;
  /** Quiz id of this module */
  quizId?: string;
  /** Id of quiz module to update */
  id: string;
}

export interface SuccessResponseTypeDtoQuizModuleDto9 {
  /** HTTP status code */
  statusCode: number;
  /** Response message */
  message: string;
  /** Updated successfully */
  data: QuizModuleDto;
}

export interface SuccessResponseTypeDtoString10 {
  /** HTTP status code */
  statusCode: number;
  /** Response message */
  message: string;
  /** Deleted successfully */
  data: string[];
}

export interface QuizQuestionBaseDto {
  /** Question */
  question: string;
  /** Correct Answer */
  answer: string;
  index: number;
}

export interface CreateQuizQuestionDto {
  /** Module id of this question */
  moduleId: string;
  /** Array of quiz questions */
  data: QuizQuestionBaseDto[];
}

export interface QuizQuestionDto {
  id: string;
  createdAt: string;
  updatedAt: string;
  /** Question */
  question: string;
  /** Correct Answer */
  answer: string;
  index: number;
}

export interface SuccessResponseTypeDtoQuizQuestionDto11 {
  /** HTTP status code */
  statusCode: number;
  /** Response message */
  message: string;
  /** Created successfully */
  data: QuizQuestionDto[];
}

export interface SuccessResponseTypeDtoQuizQuestionDto12 {
  /** HTTP status code */
  statusCode: number;
  /** Response message */
  message: string;
  /** Retrieved successfully */
  data: QuizQuestionDto[];
}

export interface SuccessResponseTypeDtoQuizQuestionDto13 {
  /** HTTP status code */
  statusCode: number;
  /** Response message */
  message: string;
  /** Retrieved successfully */
  data: QuizQuestionDto;
}

export interface UpdateQuizQuestionDto {
  /** Question */
  question?: string;
  /** Correct Answer */
  answer?: string;
  index?: number;
  /** Module id of this question */
  moduleId?: string;
  /** Id of quiz question to update */
  id: string;
}

export interface SuccessResponseTypeDtoQuizQuestionDto14 {
  /** HTTP status code */
  statusCode: number;
  /** Response message */
  message: string;
  /** Updated successfully */
  data: QuizQuestionDto;
}

export interface SuccessResponseTypeDtoString15 {
  /** HTTP status code */
  statusCode: number;
  /** Response message */
  message: string;
  /** Deleted successfully */
  data: string[];
}

export interface CreateLobbyDto {
  /** A unique code for this lobby */
  code: string;
  /** Name of the lobby */
  name: string;
  /** Till when, we will wait for other player in lobby */
  waitUntil: string;
  /** Quiz id */
  quizId: string;
}

/**
 * Status of Lobby
 */
export type QuizLobbyDtoStatus =
  (typeof QuizLobbyDtoStatus)[keyof typeof QuizLobbyDtoStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const QuizLobbyDtoStatus = {
  IN_LOBBY: "IN_LOBBY",
  WAITING_FOR_NEXT_QUESTION: "WAITING_FOR_NEXT_QUESTION",
  MODULE_BREAK: "MODULE_BREAK",
  IN_QUIZ: "IN_QUIZ",
  QUESTION_RESPONSE_SUMMARY: "QUESTION_RESPONSE_SUMMARY",
  QUIZ_SUMMARY: "QUIZ_SUMMARY",
  ENDED: "ENDED",
} as const;

export interface QuizLobbyDto {
  id: string;
  createdAt: string;
  updatedAt: string;
  /** A unique code for this lobby */
  code: string;
  /** Name of the lobby */
  name: string;
  /** Till when, we will wait for other player in lobby */
  waitUntil: string;
  /** Status of Lobby */
  status: QuizLobbyDtoStatus;
}

export interface SuccessResponseTypeDtoQuizLobbyDto16 {
  /** HTTP status code */
  statusCode: number;
  /** Response message */
  message: string;
  /** Retrieved successfully */
  data: QuizLobbyDto;
}

export interface SuccessResponseTypeDtoQuizLobbyDto17 {
  /** HTTP status code */
  statusCode: number;
  /** Response message */
  message: string;
  /** Retrieved successfully */
  data: QuizLobbyDto[];
}

export interface SuccessResponseTypeDtoQuizLobbyDto18 {
  /** HTTP status code */
  statusCode: number;
  /** Response message */
  message: string;
  /** Retrieved successfully */
  data: QuizLobbyDto;
}

/**
 * Status of Lobby
 */
export type FindJoinedLobbyResponseDtoStatus =
  (typeof FindJoinedLobbyResponseDtoStatus)[keyof typeof FindJoinedLobbyResponseDtoStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const FindJoinedLobbyResponseDtoStatus = {
  IN_LOBBY: "IN_LOBBY",
  WAITING_FOR_NEXT_QUESTION: "WAITING_FOR_NEXT_QUESTION",
  MODULE_BREAK: "MODULE_BREAK",
  IN_QUIZ: "IN_QUIZ",
  QUESTION_RESPONSE_SUMMARY: "QUESTION_RESPONSE_SUMMARY",
  QUIZ_SUMMARY: "QUIZ_SUMMARY",
  ENDED: "ENDED",
} as const;

export interface FindJoinedLobbyResponseDto {
  id: string;
  createdAt: string;
  updatedAt: string;
  /** A unique code for this lobby */
  code: string;
  /** Name of the lobby */
  name: string;
  /** Till when, we will wait for other player in lobby */
  waitUntil: string;
  /** Status of Lobby */
  status: FindJoinedLobbyResponseDtoStatus;
  quiz: QuizDto;
  currentModule: QuizModuleDto;
  currentQuestion: QuizQuestionDto;
}

export interface SuccessResponseTypeDtoFindJoinedLobbyResponseDto19 {
  /** HTTP status code */
  statusCode: number;
  /** Response message */
  message: string;
  /** Retrieved successfully */
  data: FindJoinedLobbyResponseDto;
}

export interface User {
  [key: string]: unknown;
}

/**
 * Status of Lobby
 */
export type GetLobbyByIdResponseDtoStatus =
  (typeof GetLobbyByIdResponseDtoStatus)[keyof typeof GetLobbyByIdResponseDtoStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetLobbyByIdResponseDtoStatus = {
  IN_LOBBY: "IN_LOBBY",
  WAITING_FOR_NEXT_QUESTION: "WAITING_FOR_NEXT_QUESTION",
  MODULE_BREAK: "MODULE_BREAK",
  IN_QUIZ: "IN_QUIZ",
  QUESTION_RESPONSE_SUMMARY: "QUESTION_RESPONSE_SUMMARY",
  QUIZ_SUMMARY: "QUIZ_SUMMARY",
  ENDED: "ENDED",
} as const;

export interface GetLobbyByIdResponseDto {
  id: string;
  createdAt: string;
  updatedAt: string;
  /** A unique code for this lobby */
  code: string;
  /** Name of the lobby */
  name: string;
  /** Till when, we will wait for other player in lobby */
  waitUntil: string;
  /** Status of Lobby */
  status: GetLobbyByIdResponseDtoStatus;
  quiz: QuizDto;
  participants: User[];
  currentModule: QuizModuleDto;
  currentQuestion: QuizQuestionDto;
}

export interface SuccessResponseTypeDtoGetLobbyByIdResponseDto20 {
  /** HTTP status code */
  statusCode: number;
  /** Response message */
  message: string;
  /** Retrieved successfully */
  data: GetLobbyByIdResponseDto;
}

export interface SuccessResponseTypeDtoString21 {
  /** HTTP status code */
  statusCode: number;
  /** Response message */
  message: string;
  /** Deleted successfully */
  data: string[];
}

export interface LobbyPlayerResponseDto {
  id: string;
  createdAt: string;
  updatedAt: string;
  answer: string;
  isCorrect: boolean;
  player: User;
}

export interface SuccessResponseTypeDtoLobbyPlayerResponseDto22 {
  /** HTTP status code */
  statusCode: number;
  /** Response message */
  message: string;
  /** Retrieved successfully */
  data: LobbyPlayerResponseDto[];
}

export interface EvaluateQuestionDto {
  /** Lobby id */
  lobbyId: string;
}

export interface SuccessResponseTypeDtoGetLobbyByIdResponseDto23 {
  /** HTTP status code */
  statusCode: number;
  /** Response message */
  message: string;
  /** Retrieved successfully */
  data: GetLobbyByIdResponseDto;
}

export interface QuizParticipantBaseDto {
  /** Email of the participant */
  email: string;
}

export interface CreateQuizParticipantsDto {
  /** Quiz id for participants */
  quizId: string;
  data: QuizParticipantBaseDto[];
}

export interface QuizParticipantDto {
  id: string;
  createdAt: string;
  updatedAt: string;
  /** Email of the participant */
  email: string;
}

export interface SuccessResponseTypeDtoQuizParticipantDto24 {
  /** HTTP status code */
  statusCode: number;
  /** Response message */
  message: string;
  /** Created successfully */
  data: QuizParticipantDto[];
}

export interface SuccessResponseTypeDtoQuizParticipantDto25 {
  /** HTTP status code */
  statusCode: number;
  /** Response message */
  message: string;
  /** Retrieved successfully */
  data: QuizParticipantDto[];
}

export interface SuccessResponseTypeDtoString26 {
  /** HTTP status code */
  statusCode: number;
  /** Response message */
  message: string;
  /** Deleted successfully */
  data: string[];
}

/**
 * Status of Lobby
 */
export type UpdateLobbyDtoStatus =
  (typeof UpdateLobbyDtoStatus)[keyof typeof UpdateLobbyDtoStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdateLobbyDtoStatus = {
  IN_LOBBY: "IN_LOBBY",
  WAITING_FOR_NEXT_QUESTION: "WAITING_FOR_NEXT_QUESTION",
  MODULE_BREAK: "MODULE_BREAK",
  IN_QUIZ: "IN_QUIZ",
  QUESTION_RESPONSE_SUMMARY: "QUESTION_RESPONSE_SUMMARY",
  QUIZ_SUMMARY: "QUIZ_SUMMARY",
  ENDED: "ENDED",
} as const;

export interface UpdateLobbyDto {
  /** Till when, we will wait for other player in lobby */
  waitUntil?: string;
  /** Status of Lobby */
  status?: UpdateLobbyDtoStatus;
  /** Lobby id */
  id: string;
}

export interface JoinLobbyRoomDto {
  /** Lobby id */
  lobbyId: string;
}

export interface NextQuestionDto {
  /** Lobby id */
  lobbyId: string;
}

export type QuizzesControllerDeleteManyParams = {
  /**
   * Array of quiz ids
   */
  ids: string[];
};

export type QuizModulesControllerListParams = {
  /**
   * Quiz id
   */
  quizId: string;
};

export type QuizModulesControllerDeleteManyParams = {
  /**
   * Array of quiz modules ids
   */
  ids: string[];
};

export type QuizQuestionsControllerListParams = {
  /**
   * Module id
   */
  moduleId: string;
};

export type QuizQuestionsControllerDeleteManyParams = {
  /**
   * Array of quiz questions ids
   */
  ids: string[];
};

export type PlayQuizControllerListLobbiesParams = {
  /**
   * Quiz id
   */
  quizId: string;
};

export interface EvaluateQuestionDto {
  lobbyId: string;
  correctAnswerText?: string;
}

export type PlayQuizControllerEvaluateQuestionParams = EvaluateQuestionDto;

export type PlayQuizControllerDeleteLobbiesParams = {
  /**
   * Id of lobby to delete
   */
  ids: string[];
};

export type QuizParticipantsControllerListParams = {
  /**
   * Quiz id
   */
  quizId: string;
};

export type QuizParticipantsControllerDeleteManyParams = {
  /**
   * Array of quiz participant ids
   */
  ids: string[];
};

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export const getAPIDocsGoogleMaestro001Alpha = () => {
  /**
 * 
Returns 'Hello World', useful for health check.

 * @summary Get Hello
 */
  const appControllerGetHello = (
    options?: SecondParameter<typeof apiClient<void>>
  ) => {
    return apiClient<void>({ url: `/api`, method: "GET" }, options);
  };

  /**
   * @summary Create Quiz
   */
  const quizzesControllerCreate = (
    createQuizDto: CreateQuizDto,
    options?: SecondParameter<typeof apiClient<SuccessResponseTypeDtoQuizDto1>>
  ) => {
    return apiClient<SuccessResponseTypeDtoQuizDto1>(
      {
        url: `/api/quizzes`,
        method: "POST",
        headers: { "Content-Type": "application/json" },
        data: createQuizDto,
      },
      options
    );
  };

  /**
   * @summary List quizzes
   */
  const quizzesControllerListAll = (
    options?: SecondParameter<typeof apiClient<SuccessResponseTypeDtoQuizDto2>>
  ) => {
    return apiClient<SuccessResponseTypeDtoQuizDto2>(
      { url: `/api/quizzes`, method: "GET" },
      options
    );
  };

  /**
   * @summary Update quiz by given id
   */
  const quizzesControllerUpdate = (
    updateQuizDto: UpdateQuizDto,
    options?: SecondParameter<typeof apiClient<SuccessResponseTypeDtoQuizDto4>>
  ) => {
    return apiClient<SuccessResponseTypeDtoQuizDto4>(
      {
        url: `/api/quizzes`,
        method: "PATCH",
        headers: { "Content-Type": "application/json" },
        data: updateQuizDto,
      },
      options
    );
  };

  /**
   * @summary Delete quizzes
   */
  const quizzesControllerDeleteMany = (
    params: QuizzesControllerDeleteManyParams,
    options?: SecondParameter<typeof apiClient<SuccessResponseTypeDtoString5>>
  ) => {
    return apiClient<SuccessResponseTypeDtoString5>(
      { url: `/api/quizzes`, method: "DELETE", params },
      options
    );
  };

  /**
   * @summary Get quiz by id
   */
  const quizzesControllerFindById = (
    quizId: string,
    options?: SecondParameter<typeof apiClient<SuccessResponseTypeDtoQuizDto3>>
  ) => {
    return apiClient<SuccessResponseTypeDtoQuizDto3>(
      { url: `/api/quizzes/${quizId}`, method: "GET" },
      options
    );
  };

  /**
   * @summary Create Quiz Module
   */
  const quizModulesControllerCreate = (
    createQuizModuleDto: CreateQuizModuleDto,
    options?: SecondParameter<
      typeof apiClient<SuccessResponseTypeDtoQuizModuleDto6>
    >
  ) => {
    return apiClient<SuccessResponseTypeDtoQuizModuleDto6>(
      {
        url: `/api/quiz/modules`,
        method: "POST",
        headers: { "Content-Type": "application/json" },
        data: createQuizModuleDto,
      },
      options
    );
  };

  /**
   * @summary List quiz modules
   */
  const quizModulesControllerList = (
    params: QuizModulesControllerListParams,
    options?: SecondParameter<
      typeof apiClient<SuccessResponseTypeDtoQuizModuleDto7>
    >
  ) => {
    return apiClient<SuccessResponseTypeDtoQuizModuleDto7>(
      { url: `/api/quiz/modules`, method: "GET", params },
      options
    );
  };

  /**
   * @summary Update quiz module by given id
   */
  const quizModulesControllerUpdate = (
    updateQuizModuleDto: UpdateQuizModuleDto,
    options?: SecondParameter<
      typeof apiClient<SuccessResponseTypeDtoQuizModuleDto9>
    >
  ) => {
    return apiClient<SuccessResponseTypeDtoQuizModuleDto9>(
      {
        url: `/api/quiz/modules`,
        method: "PATCH",
        headers: { "Content-Type": "application/json" },
        data: updateQuizModuleDto,
      },
      options
    );
  };

  /**
   * @summary Delete quiz modules
   */
  const quizModulesControllerDeleteMany = (
    params: QuizModulesControllerDeleteManyParams,
    options?: SecondParameter<typeof apiClient<SuccessResponseTypeDtoString10>>
  ) => {
    return apiClient<SuccessResponseTypeDtoString10>(
      { url: `/api/quiz/modules`, method: "DELETE", params },
      options
    );
  };

  /**
   * @summary Get quiz module by id
   */
  const quizModulesControllerFindById = (
    moduleId: string,
    options?: SecondParameter<
      typeof apiClient<SuccessResponseTypeDtoQuizModuleDto8>
    >
  ) => {
    return apiClient<SuccessResponseTypeDtoQuizModuleDto8>(
      { url: `/api/quiz/modules/${moduleId}`, method: "GET" },
      options
    );
  };

  /**
   * @summary Create Quiz Question
   */
  const quizQuestionsControllerCreate = (
    createQuizQuestionDto: CreateQuizQuestionDto,
    options?: SecondParameter<
      typeof apiClient<SuccessResponseTypeDtoQuizQuestionDto11>
    >
  ) => {
    return apiClient<SuccessResponseTypeDtoQuizQuestionDto11>(
      {
        url: `/api/quiz/questions`,
        method: "POST",
        headers: { "Content-Type": "application/json" },
        data: createQuizQuestionDto,
      },
      options
    );
  };

  /**
   * @summary List questions
   */
  const quizQuestionsControllerList = (
    params: QuizQuestionsControllerListParams,
    options?: SecondParameter<
      typeof apiClient<SuccessResponseTypeDtoQuizQuestionDto12>
    >
  ) => {
    return apiClient<SuccessResponseTypeDtoQuizQuestionDto12>(
      { url: `/api/quiz/questions`, method: "GET", params },
      options
    );
  };

  /**
   * @summary Update question by given id
   */
  const quizQuestionsControllerUpdate = (
    updateQuizQuestionDto: UpdateQuizQuestionDto,
    options?: SecondParameter<
      typeof apiClient<SuccessResponseTypeDtoQuizQuestionDto14>
    >
  ) => {
    return apiClient<SuccessResponseTypeDtoQuizQuestionDto14>(
      {
        url: `/api/quiz/questions`,
        method: "PATCH",
        headers: { "Content-Type": "application/json" },
        data: updateQuizQuestionDto,
      },
      options
    );
  };

  /**
   * @summary Delete quiz modules
   */
  const quizQuestionsControllerDeleteMany = (
    params: QuizQuestionsControllerDeleteManyParams,
    options?: SecondParameter<typeof apiClient<SuccessResponseTypeDtoString15>>
  ) => {
    return apiClient<SuccessResponseTypeDtoString15>(
      { url: `/api/quiz/questions`, method: "DELETE", params },
      options
    );
  };

  /**
   * @summary Get question by id
   */
  const quizQuestionsControllerFindById = (
    questionId: string,
    options?: SecondParameter<
      typeof apiClient<SuccessResponseTypeDtoQuizQuestionDto13>
    >
  ) => {
    return apiClient<SuccessResponseTypeDtoQuizQuestionDto13>(
      { url: `/api/quiz/questions/${questionId}`, method: "GET" },
      options
    );
  };

  /**
   * @summary Create a lobby
   */
  const playQuizControllerCreateLobby = (
    createLobbyDto: CreateLobbyDto,
    options?: SecondParameter<
      typeof apiClient<SuccessResponseTypeDtoQuizLobbyDto16>
    >
  ) => {
    return apiClient<SuccessResponseTypeDtoQuizLobbyDto16>(
      {
        url: `/api/quiz/play/lobby`,
        method: "POST",
        headers: { "Content-Type": "application/json" },
        data: createLobbyDto,
      },
      options
    );
  };

  /**
   * @summary List lobbies
   */
  const playQuizControllerListLobbies = (
    params: PlayQuizControllerListLobbiesParams,
    options?: SecondParameter<
      typeof apiClient<SuccessResponseTypeDtoQuizLobbyDto17>
    >
  ) => {
    return apiClient<SuccessResponseTypeDtoQuizLobbyDto17>(
      { url: `/api/quiz/play/lobby`, method: "GET", params },
      options
    );
  };

  /**
   * @summary Delete lobbies by ids
   */
  const playQuizControllerDeleteLobbies = (
    params: PlayQuizControllerDeleteLobbiesParams,
    options?: SecondParameter<typeof apiClient<SuccessResponseTypeDtoString21>>
  ) => {
    return apiClient<SuccessResponseTypeDtoString21>(
      { url: `/api/quiz/play/lobby`, method: "DELETE", params },
      options
    );
  };

  /**
   * @summary Join a lobby by lobby code
   */
  const playQuizControllerJoinLobby = (
    code: string,
    options?: SecondParameter<
      typeof apiClient<SuccessResponseTypeDtoQuizLobbyDto18>
    >
  ) => {
    return apiClient<SuccessResponseTypeDtoQuizLobbyDto18>(
      { url: `/api/quiz/play/lobby/code/${code}`, method: "POST" },
      options
    );
  };

  /**
   * @summary Get joined lobby by id
   */
  const playQuizControllerFindJoinedLobby = (
    lobbyId: string,
    options?: SecondParameter<
      typeof apiClient<SuccessResponseTypeDtoFindJoinedLobbyResponseDto19>
    >
  ) => {
    return apiClient<SuccessResponseTypeDtoFindJoinedLobbyResponseDto19>(
      { url: `/api/quiz/play/lobby/id/${lobbyId}`, method: "GET" },
      options
    );
  };

  /**
   * @summary Get lobby by id
   */
  const playQuizControllerFindLobbyById = (
    lobbyId: string,
    options?: SecondParameter<
      typeof apiClient<SuccessResponseTypeDtoGetLobbyByIdResponseDto20>
    >
  ) => {
    return apiClient<SuccessResponseTypeDtoGetLobbyByIdResponseDto20>(
      { url: `/api/quiz/play/lobby/${lobbyId}`, method: "GET" },
      options
    );
  };

  /**
   * @summary Get lobby responses
   */
  const playQuizControllerGetLobbyResponses = (
    lobbyId: string,
    options?: SecondParameter<
      typeof apiClient<SuccessResponseTypeDtoLobbyPlayerResponseDto22>
    >
  ) => {
    return apiClient<SuccessResponseTypeDtoLobbyPlayerResponseDto22>(
      { url: `/api/quiz/play/lobby/responses/${lobbyId}`, method: "GET" },
      options
    );
  };

  /**
   * @summary Evaluate question
   */
  const playQuizControllerEvaluateQuestion = (
    evaluateQuestionDto: EvaluateQuestionDto,
    options?: SecondParameter<
      typeof apiClient<SuccessResponseTypeDtoGetLobbyByIdResponseDto23>
    >
  ) => {
    return apiClient<SuccessResponseTypeDtoGetLobbyByIdResponseDto23>(
      {
        url: `/api/quiz/play/evaluate`,
        method: "POST",
        headers: { "Content-Type": "application/json" },
        data: evaluateQuestionDto,
      },
      options
    );
  };

  /**
   * @summary Create Quiz Participants
   */
  const quizParticipantsControllerCreate = (
    createQuizParticipantsDto: CreateQuizParticipantsDto,
    options?: SecondParameter<
      typeof apiClient<SuccessResponseTypeDtoQuizParticipantDto24>
    >
  ) => {
    return apiClient<SuccessResponseTypeDtoQuizParticipantDto24>(
      {
        url: `/api/quiz/participants`,
        method: "POST",
        headers: { "Content-Type": "application/json" },
        data: createQuizParticipantsDto,
      },
      options
    );
  };

  /**
   * @summary List participants
   */
  const quizParticipantsControllerList = (
    params: QuizParticipantsControllerListParams,
    options?: SecondParameter<
      typeof apiClient<SuccessResponseTypeDtoQuizParticipantDto25>
    >
  ) => {
    return apiClient<SuccessResponseTypeDtoQuizParticipantDto25>(
      { url: `/api/quiz/participants`, method: "GET", params },
      options
    );
  };

  /**
   * @summary Delete quiz participants
   */
  const quizParticipantsControllerDeleteMany = (
    params: QuizParticipantsControllerDeleteManyParams,
    options?: SecondParameter<typeof apiClient<SuccessResponseTypeDtoString26>>
  ) => {
    return apiClient<SuccessResponseTypeDtoString26>(
      { url: `/api/quiz/participants`, method: "DELETE", params },
      options
    );
  };

  return {
    appControllerGetHello,
    quizzesControllerCreate,
    quizzesControllerListAll,
    quizzesControllerUpdate,
    quizzesControllerDeleteMany,
    quizzesControllerFindById,
    quizModulesControllerCreate,
    quizModulesControllerList,
    quizModulesControllerUpdate,
    quizModulesControllerDeleteMany,
    quizModulesControllerFindById,
    quizQuestionsControllerCreate,
    quizQuestionsControllerList,
    quizQuestionsControllerUpdate,
    quizQuestionsControllerDeleteMany,
    quizQuestionsControllerFindById,
    playQuizControllerCreateLobby,
    playQuizControllerListLobbies,
    playQuizControllerDeleteLobbies,
    playQuizControllerJoinLobby,
    playQuizControllerFindJoinedLobby,
    playQuizControllerFindLobbyById,
    playQuizControllerGetLobbyResponses,
    playQuizControllerEvaluateQuestion,
    quizParticipantsControllerCreate,
    quizParticipantsControllerList,
    quizParticipantsControllerDeleteMany,
  };
};
export type AppControllerGetHelloResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<
        typeof getAPIDocsGoogleMaestro001Alpha
      >["appControllerGetHello"]
    >
  >
>;
export type QuizzesControllerCreateResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<
        typeof getAPIDocsGoogleMaestro001Alpha
      >["quizzesControllerCreate"]
    >
  >
>;
export type QuizzesControllerListAllResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<
        typeof getAPIDocsGoogleMaestro001Alpha
      >["quizzesControllerListAll"]
    >
  >
>;
export type QuizzesControllerUpdateResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<
        typeof getAPIDocsGoogleMaestro001Alpha
      >["quizzesControllerUpdate"]
    >
  >
>;
export type QuizzesControllerDeleteManyResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<
        typeof getAPIDocsGoogleMaestro001Alpha
      >["quizzesControllerDeleteMany"]
    >
  >
>;
export type QuizzesControllerFindByIdResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<
        typeof getAPIDocsGoogleMaestro001Alpha
      >["quizzesControllerFindById"]
    >
  >
>;
export type QuizModulesControllerCreateResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<
        typeof getAPIDocsGoogleMaestro001Alpha
      >["quizModulesControllerCreate"]
    >
  >
>;
export type QuizModulesControllerListResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<
        typeof getAPIDocsGoogleMaestro001Alpha
      >["quizModulesControllerList"]
    >
  >
>;
export type QuizModulesControllerUpdateResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<
        typeof getAPIDocsGoogleMaestro001Alpha
      >["quizModulesControllerUpdate"]
    >
  >
>;
export type QuizModulesControllerDeleteManyResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<
        typeof getAPIDocsGoogleMaestro001Alpha
      >["quizModulesControllerDeleteMany"]
    >
  >
>;
export type QuizModulesControllerFindByIdResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<
        typeof getAPIDocsGoogleMaestro001Alpha
      >["quizModulesControllerFindById"]
    >
  >
>;
export type QuizQuestionsControllerCreateResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<
        typeof getAPIDocsGoogleMaestro001Alpha
      >["quizQuestionsControllerCreate"]
    >
  >
>;
export type QuizQuestionsControllerListResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<
        typeof getAPIDocsGoogleMaestro001Alpha
      >["quizQuestionsControllerList"]
    >
  >
>;
export type QuizQuestionsControllerUpdateResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<
        typeof getAPIDocsGoogleMaestro001Alpha
      >["quizQuestionsControllerUpdate"]
    >
  >
>;
export type QuizQuestionsControllerDeleteManyResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<
        typeof getAPIDocsGoogleMaestro001Alpha
      >["quizQuestionsControllerDeleteMany"]
    >
  >
>;
export type QuizQuestionsControllerFindByIdResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<
        typeof getAPIDocsGoogleMaestro001Alpha
      >["quizQuestionsControllerFindById"]
    >
  >
>;
export type PlayQuizControllerCreateLobbyResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<
        typeof getAPIDocsGoogleMaestro001Alpha
      >["playQuizControllerCreateLobby"]
    >
  >
>;
export type PlayQuizControllerListLobbiesResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<
        typeof getAPIDocsGoogleMaestro001Alpha
      >["playQuizControllerListLobbies"]
    >
  >
>;
export type PlayQuizControllerDeleteLobbiesResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<
        typeof getAPIDocsGoogleMaestro001Alpha
      >["playQuizControllerDeleteLobbies"]
    >
  >
>;
export type PlayQuizControllerJoinLobbyResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<
        typeof getAPIDocsGoogleMaestro001Alpha
      >["playQuizControllerJoinLobby"]
    >
  >
>;
export type PlayQuizControllerFindJoinedLobbyResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<
        typeof getAPIDocsGoogleMaestro001Alpha
      >["playQuizControllerFindJoinedLobby"]
    >
  >
>;
export type PlayQuizControllerFindLobbyByIdResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<
        typeof getAPIDocsGoogleMaestro001Alpha
      >["playQuizControllerFindLobbyById"]
    >
  >
>;
export type PlayQuizControllerGetLobbyResponsesResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<
        typeof getAPIDocsGoogleMaestro001Alpha
      >["playQuizControllerGetLobbyResponses"]
    >
  >
>;
export type PlayQuizControllerEvaluateQuestionResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<
        typeof getAPIDocsGoogleMaestro001Alpha
      >["playQuizControllerEvaluateQuestion"]
    >
  >
>;
export type QuizParticipantsControllerCreateResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<
        typeof getAPIDocsGoogleMaestro001Alpha
      >["quizParticipantsControllerCreate"]
    >
  >
>;
export type QuizParticipantsControllerListResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<
        typeof getAPIDocsGoogleMaestro001Alpha
      >["quizParticipantsControllerList"]
    >
  >
>;
export type QuizParticipantsControllerDeleteManyResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<
        typeof getAPIDocsGoogleMaestro001Alpha
      >["quizParticipantsControllerDeleteMany"]
    >
  >
>;
