/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * API Docs | Google Maestro | 0.0.1 | @alpha
 * OpenAPI spec version: 0.0.1
 */
import { apiClient } from '../axios';
export interface CreateQuizDto {
  /** Name of quiz */
  name: string;
  description?: string;
}

export interface QuizDto {
  id: string;
  createdAt: string;
  updatedAt: string;
  name: string;
  description?: string;
}

export interface SuccessResponseTypeDtoQuizDto1 {
  /** HTTP status code */
  statusCode: number;
  /** Response message */
  message: string;
  /** Created successfully */
  data: QuizDto;
}

export interface SuccessResponseTypeDtoQuizDto2 {
  /** HTTP status code */
  statusCode: number;
  /** Response message */
  message: string;
  /** Retrieved successfully */
  data: QuizDto[];
}

export interface UpdateQuizDto {
  /** Name of quiz */
  name?: string;
  description?: string;
  /**  Id of the quiz to update */
  id: string;
}

export interface SuccessResponseTypeDtoQuizDto3 {
  /** HTTP status code */
  statusCode: number;
  /** Response message */
  message: string;
  /** Updated successfully */
  data: QuizDto;
}

export interface ApiResponseBaseDto {
  /** HTTP status code */
  statusCode: number;
  /** Response message */
  message: string;
}

export interface CreateQuizModuleDto {
  /** Name of the Module */
  name: string;
  /**
   * The order of model, first to last ie 0 to ...
   * @minimum 0
   */
  index: number;
  /** Id of the quiz to which this model is related */
  quizId: string;
}

export interface QuizModuleDto {
  id: string;
  createdAt: string;
  updatedAt: string;
  name: string;
  index: number;
}

export interface SuccessResponseTypeDtoQuizModuleDto4 {
  /** HTTP status code */
  statusCode: number;
  /** Response message */
  message: string;
  /** Created successfully */
  data: QuizModuleDto;
}

export interface SuccessResponseTypeDtoQuizModuleDto5 {
  /** HTTP status code */
  statusCode: number;
  /** Response message */
  message: string;
  /** Retrieved successfully */
  data: QuizModuleDto[];
}

export interface UpdateQuizModuleDto {
  /** Name of the Module */
  name?: string;
  /**
   * The order of model, first to last ie 0 to ...
   * @minimum 0
   */
  index?: number;
  /** Id of the quiz to which this model is related */
  quizId?: string;
  /**  Id of the quiz module to update */
  id: string;
}

export interface SuccessResponseTypeDtoQuizModuleDto6 {
  /** HTTP status code */
  statusCode: number;
  /** Response message */
  message: string;
  /** Updated successfully */
  data: QuizModuleDto;
}

export type QuizzesControllerDeleteQuizzesParams = {
/**
 * @minLength 1
 */
ids: string[];
};

export type QuizzesControllerListQuizModulesParams = {
/**
 *  Id of the quiz to to list modules for
 */
id: string;
};

export type QuizzesControllerDeleteQuizModulesParams = {
/**
 * @minLength 1
 */
ids: string[];
};

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  export const getAPIDocsGoogleMaestro001Alpha = () => {
const appControllerGetHello = (
    
 options?: SecondParameter<typeof apiClient<void>>,) => {
      return apiClient<void>(
      {url: `/api`, method: 'GET'
    },
      options);
    }
  
/**
 * No description available
 * @summary Create a quiz
 */
const quizzesControllerCreateQuiz = (
    createQuizDto: CreateQuizDto,
 options?: SecondParameter<typeof apiClient<SuccessResponseTypeDtoQuizDto1>>,) => {
      return apiClient<SuccessResponseTypeDtoQuizDto1>(
      {url: `/api/quizzes`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createQuizDto
    },
      options);
    }
  
/**
 * No description available
 * @summary List all avaliable quizes
 */
const quizzesControllerListAllQuizzes = (
    
 options?: SecondParameter<typeof apiClient<SuccessResponseTypeDtoQuizDto2>>,) => {
      return apiClient<SuccessResponseTypeDtoQuizDto2>(
      {url: `/api/quizzes`, method: 'GET'
    },
      options);
    }
  
/**
 * No description available
 * @summary Update quiz
 */
const quizzesControllerUpdateQuiz = (
    updateQuizDto: UpdateQuizDto,
 options?: SecondParameter<typeof apiClient<SuccessResponseTypeDtoQuizDto3>>,) => {
      return apiClient<SuccessResponseTypeDtoQuizDto3>(
      {url: `/api/quizzes`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: updateQuizDto
    },
      options);
    }
  
/**
 * No description available
 * @summary Delete quizzes by givn IDs
 */
const quizzesControllerDeleteQuizzes = (
    params: QuizzesControllerDeleteQuizzesParams,
 options?: SecondParameter<typeof apiClient<ApiResponseBaseDto>>,) => {
      return apiClient<ApiResponseBaseDto>(
      {url: `/api/quizzes`, method: 'DELETE',
        params
    },
      options);
    }
  
/**
 * No description available
 * @summary Add a quiz module
 */
const quizzesControllerCreateQuizModule = (
    createQuizModuleDto: CreateQuizModuleDto,
 options?: SecondParameter<typeof apiClient<SuccessResponseTypeDtoQuizModuleDto4>>,) => {
      return apiClient<SuccessResponseTypeDtoQuizModuleDto4>(
      {url: `/api/quizzes/modules`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createQuizModuleDto
    },
      options);
    }
  
/**
 * No description available
 * @summary List quiz modules ordered by index asc
 */
const quizzesControllerListQuizModules = (
    params: QuizzesControllerListQuizModulesParams,
 options?: SecondParameter<typeof apiClient<SuccessResponseTypeDtoQuizModuleDto5>>,) => {
      return apiClient<SuccessResponseTypeDtoQuizModuleDto5>(
      {url: `/api/quizzes/modules`, method: 'GET',
        params
    },
      options);
    }
  
/**
 * No description available
 * @summary Update quiz module
 */
const quizzesControllerUpdateQuizModule = (
    updateQuizModuleDto: UpdateQuizModuleDto,
 options?: SecondParameter<typeof apiClient<SuccessResponseTypeDtoQuizModuleDto6>>,) => {
      return apiClient<SuccessResponseTypeDtoQuizModuleDto6>(
      {url: `/api/quizzes/modules`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: updateQuizModuleDto
    },
      options);
    }
  
/**
 * No description available
 * @summary Delete quiz modules
 */
const quizzesControllerDeleteQuizModules = (
    params: QuizzesControllerDeleteQuizModulesParams,
 options?: SecondParameter<typeof apiClient<ApiResponseBaseDto>>,) => {
      return apiClient<ApiResponseBaseDto>(
      {url: `/api/quizzes/modules`, method: 'DELETE',
        params
    },
      options);
    }
  
return {appControllerGetHello,quizzesControllerCreateQuiz,quizzesControllerListAllQuizzes,quizzesControllerUpdateQuiz,quizzesControllerDeleteQuizzes,quizzesControllerCreateQuizModule,quizzesControllerListQuizModules,quizzesControllerUpdateQuizModule,quizzesControllerDeleteQuizModules}};
export type AppControllerGetHelloResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAPIDocsGoogleMaestro001Alpha>['appControllerGetHello']>>>
export type QuizzesControllerCreateQuizResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAPIDocsGoogleMaestro001Alpha>['quizzesControllerCreateQuiz']>>>
export type QuizzesControllerListAllQuizzesResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAPIDocsGoogleMaestro001Alpha>['quizzesControllerListAllQuizzes']>>>
export type QuizzesControllerUpdateQuizResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAPIDocsGoogleMaestro001Alpha>['quizzesControllerUpdateQuiz']>>>
export type QuizzesControllerDeleteQuizzesResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAPIDocsGoogleMaestro001Alpha>['quizzesControllerDeleteQuizzes']>>>
export type QuizzesControllerCreateQuizModuleResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAPIDocsGoogleMaestro001Alpha>['quizzesControllerCreateQuizModule']>>>
export type QuizzesControllerListQuizModulesResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAPIDocsGoogleMaestro001Alpha>['quizzesControllerListQuizModules']>>>
export type QuizzesControllerUpdateQuizModuleResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAPIDocsGoogleMaestro001Alpha>['quizzesControllerUpdateQuizModule']>>>
export type QuizzesControllerDeleteQuizModulesResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAPIDocsGoogleMaestro001Alpha>['quizzesControllerDeleteQuizModules']>>>
