export enum ICONS_ENUM {
  // use cases related icons
  LOGIN_LINK = "LOGIN_LINK",
  CREATE_ORGANIZATION = "CREATE_ORGANIZATION",
  INVITE_USER = "INVITE_USER",
  LIGHT_MODE = "LIGHT_MODE",
  DARK_MODE = "DARK_MODE",

  // general icons
  ORGANIZATION = "ORGANIZATION",
  USERNAME = "USERNAME",
  MAIL = "MAIL",
  CHECK = "CHECK",
  X = "X",
  COPY = "COPY",
  ANONYMOUS_AVATAR = "ANONYMOUS_AVATAR",
  GOOGLE = "GOOGLE",
  SPINNER = "SPINNER",
  CHEVRON_UP_DOWN = "CHEVRON_UP_DOWN",
  PLUS = "PLUS",
  OPTIONS = "OPTIONS",
  LOG_OUT = "LOG_OUT",
  USER = "USER",
  ADMIN = "ADMIN",
  SETTINGS = "SETTINGS",
  CHEVRON_RIGHT = "CHEVRON_RIGHT",
  PLUGINS = "PLUGINS",
  SEARCH = "SEARCH",
  USERS = "USERS",
  TRASH = "TRASH",
  REFRESH = "REFRESH",
  ADJUSTMENTS = "ADJUSTMENTS",

  // sorting icons
  SORT_ASC = "SORT_ASC",
  SORT_DESC = "SORT_DESC",
  SORT_NONE = "SORT_NONE",
}
