import fs from "fs";

const cwd = process.cwd();

const pluginsDir = `${cwd}/plugins`;
const pluginsTsPath = `${cwd}/lib/plugin-loader/src/plugins.ts`;
const pluginsInfoPath = `${cwd}/lib/plugin-loader/src/plugins-info.ts`;

// Discover all plugins: dir name, package name, and module entry
const pluginDirs = fs
  .readdirSync(pluginsDir)
  .filter((file) => fs.statSync(`${pluginsDir}/${file}`).isDirectory());

const pluginEntries: {
  name: string;
  description: string;
  version: string;
  dir: string;
  moduleEntry: string;
}[] = [];

for (const dir of pluginDirs) {
  const packageJsonPath = `${pluginsDir}/${dir}/package.json`;
  if (!fs.existsSync(packageJsonPath)) continue;
  const packageJson = JSON.parse(fs.readFileSync(packageJsonPath, "utf-8"));
  const name = packageJson.name;
  if (!name) continue;
  const moduleEntry = packageJson.module ?? "src/index.ts";
  pluginEntries.push({
    name,
    description: packageJson.description ?? "",
    version: packageJson.version ?? "",
    dir,
    moduleEntry,
  });
}

const pluginNames = pluginEntries.map((e) => e.name);

// 1. Write plugins.ts (import map)
const pluginsTsContent = `// @ts-nocheck
// This file is auto-generated by scripts/save-plugins-import.ts. Do not edit this file manually.
// To update the plugins, run: bun run plugins:save
export const PLUGINS: Record<string, () => Promise<any>> = {
${pluginNames.map((name) => `  "${name}": () => import("${name}"),`).join("\n")}
};
`;

fs.writeFileSync(pluginsTsPath, pluginsTsContent);
console.log(`Plugins import file generated at ${pluginsTsPath}`);

// 2. Update plugin-loader package.json with plugins as dependencies
const pluginLoaderPackageJsonPath = `${cwd}/lib/plugin-loader/package.json`;
const pluginLoaderPackageJson = JSON.parse(
  fs.readFileSync(pluginLoaderPackageJsonPath, "utf-8"),
);

pluginLoaderPackageJson.dependencies = {
  ...pluginLoaderPackageJson.dependencies,
  ...Object.fromEntries(pluginNames.map((name) => [name, "workspace:*"])),
};

fs.writeFileSync(
  pluginLoaderPackageJsonPath,
  JSON.stringify(pluginLoaderPackageJson, null, 2),
);
console.log(`Plugin loader package.json updated with plugins as dependencies.`);

// 3. Parse each plugin's src/index.ts for config fields (no import — avoids pulling in plugin-loader)
const pluginsInfo: Record<string, Record<string, unknown>> = {};

function parseDefineConfigFields(source: string): {
  type?: string;
  status?: string;
  targetVersion?: string;
  scope?: string[];
} {
  const typeMatch = source.match(/type:\s*["']([^"']+)["']/);
  const statusMatch = source.match(/status:\s*["']([^"']+)["']/);
  const targetVersionMatch = source.match(/targetVersion:\s*["']([^"']+)["']/);
  const scopeMatch = source.match(/scope:\s*\[\s*([^\]]+)\]/);
  const scope = scopeMatch
    ? scopeMatch[1]
        ?.split(",")
        .map((s) => s.replace(/["'\s]/g, "").trim())
        .filter(Boolean)
    : undefined;
  return {
    type: typeMatch?.[1],
    status: statusMatch?.[1],
    targetVersion: targetVersionMatch?.[1],
    scope,
  };
}

for (const { name, description, version, dir, moduleEntry } of pluginEntries) {
  const entryPath = `${pluginsDir}/${dir}/${moduleEntry}`;
  if (!fs.existsSync(entryPath)) {
    console.warn(`Skipping ${name}: entry not found at ${entryPath}`);
    continue;
  }
  const source = fs.readFileSync(entryPath, "utf-8");
  const parsed = parseDefineConfigFields(source);
  pluginsInfo[name] = {
    name,
    description,
    version,
    type: parsed.type,
    status: parsed.status,
    targetVersion: parsed.targetVersion,
    scope: parsed.scope,
  };
}

const pluginsInfoContent = `// @ts-nocheck
// This file is auto-generated by scripts/save-plugins-import.ts. Do not edit this file manually.
// To update, run: bun run plugins:save

export const PLUGINS_INFO = ${JSON.stringify(pluginsInfo, null, 2)} as const;

export type PluginsInfo = typeof PLUGINS_INFO;
`;

fs.writeFileSync(pluginsInfoPath, pluginsInfoContent);
console.log(`Plugins info file generated at ${pluginsInfoPath}`);
