import fs from "fs";

const cwd = process.cwd();

// read all the plugins from the plugins directory and find all the package.json names as array

const pluginsDir = `${cwd}/plugins`;
const outputFile = `${cwd}/lib/plugin-loader/src/plugins.ts`;

const pluginNames = fs
  .readdirSync(pluginsDir)
  .filter((file) => fs.statSync(`${pluginsDir}/${file}`).isDirectory())
  .map((dir) => {
    const packageJsonPath = `${pluginsDir}/${dir}/package.json`;
    if (fs.existsSync(packageJsonPath)) {
      const packageJson = JSON.parse(fs.readFileSync(packageJsonPath, "utf-8"));
      return packageJson.name;
    }
    return null;
  })
  .filter((name): name is string => name !== null);

const outputContent = `// @ts-nocheck
// This file is auto-generated by scripts/save-plugins-import.ts. Do not edit this file manually.
// To update the plugins, Run: bun run plugins:save
export const PLUGINS: Record<string, () => Promise<any>> = {
${pluginNames.map((name) => `  "${name}": () => import("${name}"),`).join("\n")}
};
`;

fs.writeFileSync(outputFile, outputContent);
console.log(`Plugins import file generated at ${outputFile}`);

// Update package.json of plugin loader to include the plugins as dependencies
const pluginLoaderPackageJsonPath = `${cwd}/lib/plugin-loader/package.json`;
const pluginLoaderPackageJson = JSON.parse(
  fs.readFileSync(pluginLoaderPackageJsonPath, "utf-8"),
);

pluginLoaderPackageJson.dependencies = {
  ...pluginLoaderPackageJson.dependencies,
  ...Object.fromEntries(pluginNames.map((name) => [name, "workspace:*"])),
};

fs.writeFileSync(
  pluginLoaderPackageJsonPath,
  JSON.stringify(pluginLoaderPackageJson, null, 2),
);
console.log(`Plugin loader package.json updated with plugins as dependencies.`);
