export const ROLE = {
  ADMIN: "admin",
  USER: "user",
} as const;

export const LOBBY_STATUS = {
  IN_LOBBY: "IN_LOBBY",
  WAITING_FOR_NEXT_QUESTION: "WAITING_FOR_NEXT_QUESTION",
  MODULE_BREAK: "MODULE_BREAK",
  IN_QUIZ: "IN_QUIZ",
  ENDED: "ENDED",
  QUESTION_RESPONSE_SUMMARY: "QUESTION_RESPONSE_SUMMARY",
  QUIZ_SUMMARY: "QUIZ_SUMMARY",
} as const;
